export const cssDescriptionKeys = {
  '--moduix-accordion-color': 'cssDescriptionModuixAccordionColor',
  '--moduix-accordion-disabled-opacity': 'cssDescriptionModuixAccordionDisabledOpacity',
  '--moduix-accordion-focus-ring-color': 'cssDescriptionModuixAccordionFocusRingColor',
  '--moduix-accordion-focus-ring-offset': 'cssDescriptionModuixAccordionFocusRingOffset',
  '--moduix-accordion-focus-ring-width': 'cssDescriptionModuixAccordionFocusRingWidth',
  '--moduix-accordion-horizontal-content-width':
    'cssDescriptionModuixAccordionHorizontalContentWidth',
  '--moduix-accordion-horizontal-height': 'cssDescriptionModuixAccordionHorizontalHeight',
  '--moduix-accordion-horizontal-max-height': 'cssDescriptionModuixAccordionHorizontalMaxHeight',
  '--moduix-accordion-horizontal-trigger-width':
    'cssDescriptionModuixAccordionHorizontalTriggerWidth',
  '--moduix-accordion-horizontal-width': 'cssDescriptionModuixAccordionHorizontalWidth',
  '--moduix-accordion-icon-open-transform': 'cssDescriptionModuixAccordionIconOpenTransform',
  '--moduix-accordion-icon-size': 'cssDescriptionModuixAccordionIconSize',
  '--moduix-accordion-icon-transition': 'cssDescriptionModuixAccordionIconTransition',
  '--moduix-accordion-item-border-color': 'cssDescriptionModuixAccordionItemBorderColor',
  '--moduix-accordion-item-border-width': 'cssDescriptionModuixAccordionItemBorderWidth',
  '--moduix-accordion-item-body-gap': 'cssDescriptionModuixAccordionItemBodyGap',
  '--moduix-accordion-item-body-padding': 'cssDescriptionModuixAccordionItemBodyPadding',
  '--moduix-accordion-item-content-closed-opacity':
    'cssDescriptionModuixAccordionItemContentClosedOpacity',
  '--moduix-accordion-item-content-color': 'cssDescriptionModuixAccordionItemContentColor',
  '--moduix-accordion-item-content-font-size': 'cssDescriptionModuixAccordionItemContentFontSize',
  '--moduix-accordion-item-content-line-height':
    'cssDescriptionModuixAccordionItemContentLineHeight',
  '--moduix-accordion-item-content-open-opacity':
    'cssDescriptionModuixAccordionItemContentOpenOpacity',
  '--moduix-accordion-item-content-transition':
    'cssDescriptionModuixAccordionItemContentTransition',
  '--moduix-accordion-max-width': 'cssDescriptionModuixAccordionMaxWidth',
  '--moduix-accordion-trigger-bg': 'cssDescriptionModuixAccordionTriggerBg',
  '--moduix-accordion-trigger-bg-active': 'cssDescriptionModuixAccordionTriggerBgActive',
  '--moduix-accordion-trigger-bg-hover': 'cssDescriptionModuixAccordionTriggerBgHover',
  '--moduix-accordion-trigger-font-size': 'cssDescriptionModuixAccordionTriggerFontSize',
  '--moduix-accordion-trigger-gap': 'cssDescriptionModuixAccordionTriggerGap',
  '--moduix-accordion-trigger-line-height': 'cssDescriptionModuixAccordionTriggerLineHeight',
  '--moduix-accordion-trigger-padding-x': 'cssDescriptionModuixAccordionTriggerPaddingX',
  '--moduix-accordion-trigger-padding-y': 'cssDescriptionModuixAccordionTriggerPaddingY',
  '--moduix-accordion-width': 'cssDescriptionModuixAccordionWidth',
  '--moduix-alert-actions-gap': 'cssDescriptionModuixAlertActionsGap',
  '--moduix-alert-actions-margin-top': 'cssDescriptionModuixAlertActionsMarginTop',
  '--moduix-alert-bg': 'cssDescriptionModuixAlertBg',
  '--moduix-alert-bg-default': 'cssDescriptionModuixAlertBgDefault',
  '--moduix-alert-border-color': 'cssDescriptionModuixAlertBorderColor',
  '--moduix-alert-border-color-default': 'cssDescriptionModuixAlertBorderColorDefault',
  '--moduix-alert-border-width': 'cssDescriptionModuixAlertBorderWidth',
  '--moduix-alert-color': 'cssDescriptionModuixAlertColor',
  '--moduix-alert-color-default': 'cssDescriptionModuixAlertColorDefault',
  '--moduix-alert-content-gap': 'cssDescriptionModuixAlertContentGap',
  '--moduix-alert-description-color': 'cssDescriptionModuixAlertDescriptionColor',
  '--moduix-alert-description-font-size': 'cssDescriptionModuixAlertDescriptionFontSize',
  '--moduix-alert-description-line-height': 'cssDescriptionModuixAlertDescriptionLineHeight',
  '--moduix-alert-gap': 'cssDescriptionModuixAlertGap',
  '--moduix-alert-indicator-color': 'cssDescriptionModuixAlertIndicatorColor',
  '--moduix-alert-indicator-color-default': 'cssDescriptionModuixAlertIndicatorColorDefault',
  '--moduix-alert-indicator-offset': 'cssDescriptionModuixAlertIndicatorOffset',
  '--moduix-alert-indicator-size': 'cssDescriptionModuixAlertIndicatorSize',
  '--moduix-alert-padding': 'cssDescriptionModuixAlertPadding',
  '--moduix-alert-radius': 'cssDescriptionModuixAlertRadius',
  '--moduix-alert-shadow': 'cssDescriptionModuixAlertShadow',
  '--moduix-color-primary': 'cssDescriptionModuixColorPrimary',
  '--moduix-color-success': 'cssDescriptionModuixColorSuccess',
  '--moduix-alert-title-color': 'cssDescriptionModuixAlertTitleColor',
  '--moduix-alert-title-font-size': 'cssDescriptionModuixAlertTitleFontSize',
  '--moduix-alert-title-font-weight': 'cssDescriptionModuixAlertTitleFontWeight',
  '--moduix-alert-title-line-height': 'cssDescriptionModuixAlertTitleLineHeight',
  '--moduix-color-warning': 'cssDescriptionModuixColorWarning',
  '--moduix-color-destructive': 'cssDescriptionModuixColorDestructive',
  '--moduix-angle-slider-color': 'cssDescriptionModuixAngleSliderColor',
  '--moduix-angle-slider-center-dot-color': 'cssDescriptionModuixAngleSliderCenterDotColor',
  '--moduix-angle-slider-center-dot-size': 'cssDescriptionModuixAngleSliderCenterDotSize',
  '--moduix-angle-slider-control-bg': 'cssDescriptionModuixAngleSliderControlBg',
  '--moduix-angle-slider-control-border-color': 'cssDescriptionModuixAngleSliderControlBorderColor',
  '--moduix-angle-slider-control-border-width': 'cssDescriptionModuixAngleSliderControlBorderWidth',
  '--moduix-angle-slider-disabled-opacity': 'cssDescriptionModuixAngleSliderDisabledOpacity',
  '--moduix-angle-slider-focus-ring-color': 'cssDescriptionModuixAngleSliderFocusRingColor',
  '--moduix-angle-slider-focus-ring-width': 'cssDescriptionModuixAngleSliderFocusRingWidth',
  '--moduix-angle-slider-gap': 'cssDescriptionModuixAngleSliderGap',
  '--moduix-angle-slider-indicator-bg': 'cssDescriptionModuixAngleSliderIndicatorBg',
  '--moduix-angle-slider-invalid-color': 'cssDescriptionModuixAngleSliderInvalidColor',
  '--moduix-angle-slider-label-color': 'cssDescriptionModuixAngleSliderLabelColor',
  '--moduix-angle-slider-label-font-size': 'cssDescriptionModuixAngleSliderLabelFontSize',
  '--moduix-angle-slider-label-font-weight': 'cssDescriptionModuixAngleSliderLabelFontWeight',
  '--moduix-angle-slider-label-line-height': 'cssDescriptionModuixAngleSliderLabelLineHeight',
  '--moduix-angle-slider-marker-active-color': 'cssDescriptionModuixAngleSliderMarkerActiveColor',
  '--moduix-angle-slider-marker-color': 'cssDescriptionModuixAngleSliderMarkerColor',
  '--moduix-angle-slider-marker-current-color': 'cssDescriptionModuixAngleSliderMarkerCurrentColor',
  '--moduix-angle-slider-marker-height': 'cssDescriptionModuixAngleSliderMarkerHeight',
  '--moduix-angle-slider-marker-width': 'cssDescriptionModuixAngleSliderMarkerWidth',
  '--moduix-angle-slider-radius': 'cssDescriptionModuixAngleSliderRadius',
  '--moduix-angle-slider-ring-thickness': 'cssDescriptionModuixAngleSliderRingThickness',
  '--moduix-angle-slider-shadow': 'cssDescriptionModuixAngleSliderShadow',
  '--moduix-angle-slider-size': 'cssDescriptionModuixAngleSliderSize',
  '--moduix-angle-slider-thumb-bg': 'cssDescriptionModuixAngleSliderThumbBg',
  '--moduix-angle-slider-thumb-border-color': 'cssDescriptionModuixAngleSliderThumbBorderColor',
  '--moduix-angle-slider-thumb-border-width': 'cssDescriptionModuixAngleSliderThumbBorderWidth',
  '--moduix-angle-slider-thumb-line-width': 'cssDescriptionModuixAngleSliderThumbLineWidth',
  '--moduix-angle-slider-thumb-radius': 'cssDescriptionModuixAngleSliderThumbRadius',
  '--moduix-angle-slider-thumb-shadow': 'cssDescriptionModuixAngleSliderThumbShadow',
  '--moduix-angle-slider-thumb-size': 'cssDescriptionModuixAngleSliderThumbSize',
  '--moduix-angle-slider-track-bg': 'cssDescriptionModuixAngleSliderTrackBg',
  '--moduix-angle-slider-track-border-color': 'cssDescriptionModuixAngleSliderTrackBorderColor',
  '--moduix-angle-slider-track-border-width': 'cssDescriptionModuixAngleSliderTrackBorderWidth',
  '--moduix-angle-slider-transition': 'cssDescriptionModuixAngleSliderTransition',
  '--moduix-angle-slider-value-text-color': 'cssDescriptionModuixAngleSliderValueTextColor',
  '--moduix-angle-slider-value-text-font-size': 'cssDescriptionModuixAngleSliderValueTextFontSize',
  '--moduix-angle-slider-value-text-font-weight':
    'cssDescriptionModuixAngleSliderValueTextFontWeight',
  '--moduix-angle-slider-value-text-line-height':
    'cssDescriptionModuixAngleSliderValueTextLineHeight',
  '--moduix-aspect-ratio-radius': 'cssDescriptionModuixAspectRatioRadius',
  '--moduix-avatar-bg': 'cssDescriptionModuixAvatarBg',
  '--moduix-avatar-color': 'cssDescriptionModuixAvatarColor',
  '--moduix-avatar-fallback-bg': 'cssDescriptionModuixAvatarFallbackBg',
  '--moduix-avatar-fallback-color': 'cssDescriptionModuixAvatarFallbackColor',
  '--moduix-avatar-fallback-padding': 'cssDescriptionModuixAvatarFallbackPadding',
  '--moduix-avatar-font-size': 'cssDescriptionModuixAvatarFontSize',
  '--moduix-avatar-font-weight': 'cssDescriptionModuixAvatarFontWeight',
  '--moduix-avatar-image-object-fit': 'cssDescriptionModuixAvatarImageObjectFit',
  '--moduix-avatar-image-object-position': 'cssDescriptionModuixAvatarImageObjectPosition',
  '--moduix-avatar-line-height': 'cssDescriptionModuixAvatarLineHeight',
  '--moduix-avatar-radius': 'cssDescriptionModuixAvatarRadius',
  '--moduix-avatar-size': 'cssDescriptionModuixAvatarSize',
} as const;