packages:
  - website
  - packages/*
  - playgrounds/*

allowBuilds:
  esbuild: true
  fsevents: true
  sharp: true
  workerd: true

peerDependencyRules:
  allowedVersions:
    'unplugin-dts>@rspack/core': '2'

catalog:
  '@ark-ui/react': '^5.39.2'
  '@ark-ui/solid': '^5.39.2'
  '@ark-ui/vue': '^5.39.2'
  '@internationalized/date': '^3.12.4'
  '@lucide/vue': '^1.47.0'
  '@rsbuild/core': '^2.2.6'
  '@rsbuild/plugin-babel': '^2.1.0'
  '@rsbuild/plugin-react': '^2.1.0'
  '@rsbuild/plugin-solid': '^1.2.2'
  '@rsbuild/plugin-vue': '^2.0.1'
  '@rslib/core': '^1.0.0'
  '@rstest/adapter-rslib': '^0.11.12'
  '@rstest/core': '^0.11.12'
  '@solidjs/testing-library': '^0.8.10'
  '@storybook/react-vite': '^10.6.0'
  '@storybook/vue3-vite': '^10.6.0'
  '@tailwindcss/vite': '^4.3.3'
  '@tanstack/charts': '^0.16.2'
  '@testing-library/dom': '^10.4.2'
  '@testing-library/jest-dom': '^7.0.1'
  '@testing-library/react': '^16.3.3'
  '@testing-library/user-event': '^14.6.7'
  '@testing-library/vue': '^8.1.0'
  '@types/node': '^24.13.6'
  '@types/react': '^19.3.0'
  '@types/react-dom': '^19.3.0'
  '@unpic/core': '^1.0.3'
  '@unpic/react': '^1.0.2'
  '@vitejs/plugin-vue': '^6.0.9'
  '@vue/language-core': '^3.3.11'
  '@vue/server-renderer': '^3.5.43'
  'class-variance-authority': '^0.7.1'
  'clsx': '^2.1.1'
  'happy-dom': '^20.14.5'
  'lucide-react': '^1.46.0'
  'lucide-solid': '^1.46.0'
  'react': '^19.3.0'
  'react-dom': '^19.3.0'
  'solid-js': '^1.9.15'
  'storybook': '^10.6.0'
  'storybook-solidjs-vite': '^10.7.1'
  'tailwind-merge': '^3.7.0'
  'tailwindcss': '^4.3.3'
  'unplugin-dts': '^1.1.0'
  'vite': '^8.3.0'
  'vite-plugin-solid': '^2.11.14'
  'vue': '^3.5.43'
  'vue-tsc': '^3.3.11'