import { Tag as OriginalTag } from '@rspress/core/theme-original';
import {
  ArrowLeftRight,
  ArrowRightLeft,
  BadgeCheck,
  BookOpen,
  Bot,
  Braces,
  Calculator,
  ClipboardList,
  Clock3,
  Component as ComponentIcon,
  Database,
  Download,
  Eye,
  FileText,
  Frame,
  GitBranch,
  HardDrive,
  History,
  Keyboard,
  KeyRound,
  Languages,
  List,
  ListChecks,
  LoaderCircle,
  LockKeyhole,
  LogIn,
  Monitor,
  Moon,
  Orbit,
  Palette,
  Paintbrush,
  PanelLeft,
  PanelLeftOpen,
  PanelsTopLeft,
  PanelTop,
  RefreshCw,
  Rocket,
  ScrollText,
  Sparkles,
  SwatchBook,
  TableProperties,
  Upload,
  UserRoundPlus,
  UsersRound,
  Workflow,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  'arrow-left-right': ArrowLeftRight,
  'arrow-right-left': ArrowRightLeft,
  'badge-check': BadgeCheck,
  'book-open': BookOpen,
  bot: Bot,
  braces: Braces,
  calculator: Calculator,
  'clipboard-list': ClipboardList,
  clock: Clock3,
  component: ComponentIcon,
  database: Database,
  download: Download,
  eye: Eye,
  'file-text': FileText,
  frame: Frame,
  'git-branch': GitBranch,
  'hard-drive': HardDrive,
  history: History,
  keyboard: Keyboard,
  'key-round': KeyRound,
  languages: Languages,
  list: List,
  'list-checks': ListChecks,
  'loader-circle': LoaderCircle,
  'lock-keyhole': LockKeyhole,
  'log-in': LogIn,
  monitor: Monitor,
  moon: Moon,
  orbit: Orbit,
  palette: Palette,
  paintbrush: Paintbrush,
  'panel-left': PanelLeft,
  'panel-left-open': PanelLeftOpen,
  'panels-top-left': PanelsTopLeft,
  'panel-top': PanelTop,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  'scroll-text': ScrollText,
  sparkles: Sparkles,
  'swatch-book': SwatchBook,
  'table-properties': TableProperties,
  upload: Upload,
  'user-round-plus': UserRoundPlus,
  'users-round': UsersRound,
  workflow: Workflow,
  wrench: Wrench,
};

export function Tag({ tag }: { tag?: string }) {
  const Icon = tag ? icons[tag] : undefined;

  return Icon ? (
    <Icon aria-hidden="true" size="1em" strokeWidth={1.75} />
  ) : (
    <OriginalTag tag={tag} />
  );
}